# Generated by Django 3.2.13 on 2022-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images_three',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images_two',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
