# Generated by Django 3.2.13 on 2022-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code_reffered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
