# Generated by Django 3.2.13 on 2022-06-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.maincategory'),
        ),
    ]
