# Generated by Django 3.2.13 on 2022-06-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_main_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='category.maincategory'),
        ),
    ]
