# Generated by Django 3.2.13 on 2022-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
